{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "5258aadd_1a8ad9c1",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 1,
      "author": {
        "id": 1007976
      },
      "writtenOn": "2021-02-08T07:17:19Z",
      "side": 1,
      "message": "I would suggest to debug more on the error, it is most likely the error is for a different reason. The preferred way for virtualenv in python3 is via venv and its inbuilt, not requiring additional packages. so lets see how we can keep on using the preferred way",
      "revId": "a47da4d7346d46b76e389a7fa9157f6e7f543820",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "be4a6469_fc50e667",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 1,
      "author": {
        "id": 1008672
      },
      "writtenOn": "2021-02-08T09:44:24Z",
      "side": 1,
      "message": "Completely agree with Sanjay.\nUsing a builtin way of creating the virtualenv \"python -m venv \u003cvenv_path\u003e\" is a proffered and recommended way of creating the virtual environment.\n\nI would say as well that the reason for the failure is something else.\n\nLet\u0027s me know, if you need any help in debugging.",
      "parentUuid": "5258aadd_1a8ad9c1",
      "revId": "a47da4d7346d46b76e389a7fa9157f6e7f543820",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "6d08537c_16390149",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1008484
      },
      "writtenOn": "2021-02-07T21:27:39Z",
      "side": 1,
      "message": "Received -1, since this fix, tends to fix gate -1\nFYI",
      "revId": "a47da4d7346d46b76e389a7fa9157f6e7f543820",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "45a56b10_856ad47a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1008484
      },
      "writtenOn": "2021-02-08T10:39:06Z",
      "side": 1,
      "message": "Please refer this\nhttps://virtualenv.pypa.io/en/stable/\n\nvenv is subset with of virtualenv, it could be installed through pip\nand could be extendable\n\nI do not know how to move on, sorry comrades \n",
      "revId": "a47da4d7346d46b76e389a7fa9157f6e7f543820",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "c0722d35_21bd1450",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1008672
      },
      "writtenOn": "2021-02-08T10:41:09Z",
      "side": 1,
      "message": "Yariv, I\u0027m not saying your fix is wrong.\nI just think it could be another issue.\nI see it on my env as well.\n\nWill look into it and update the ticket.",
      "parentUuid": "45a56b10_856ad47a",
      "revId": "a47da4d7346d46b76e389a7fa9157f6e7f543820",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "9360a296_46f33d71",
        "filename": "roles/post_install/openstack_tasks/tasks/setup_openstack_env.yml",
        "patchSetId": 1
      },
      "lineNbr": 49,
      "author": {
        "id": 1007976
      },
      "writtenOn": "2021-02-08T07:17:19Z",
      "side": 1,
      "message": "should be virtualenv",
      "range": {
        "startLine": 49,
        "startChar": 14,
        "endLine": 49,
        "endChar": 18
      },
      "revId": "a47da4d7346d46b76e389a7fa9157f6e7f543820",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    }
  ]
}